# Generated by Django 4.2.6 on 2023-10-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_card_card_number_alter_card_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(blank=True, choices=[('stripe', 'stripe'), ('paysera', 'paysera'), ('payeer', 'payeer')], max_length=50, null=True),
        ),
    ]
